### ISSUE TITLE
The reason why pretrain does work.

### ISSUE THREAD

**Issue by guotong1988** [brightmart/bert_language_understanding#12]
Do you think that it is mainly because:
BERT is Bidirectional, and CNN could also have the same function?
@brightmart Thank you!

**Comment by brightmart** [comment]
no. it is not related to BERT or CNN.
a model, no matter which actually it is, pre-train stage is able to learn most of parameters  for that model. so during fine-tuning, you only need to learn few parameters, such as parameter for last layer as  classifier.
