### ISSUE TITLE
question on the implement of bert_cnn_model

### ISSUE THREAD

**Issue by zhhongzhi** [brightmart/bert_language_understanding#4]
Very interesting work which indicates Pre-training can be every where (small scale, cnn models). 

I have a question on the implement of `bert_cnn_model.py`.  
`        # 3. get last hidden state of the masked position(s), and project it to make a predict.
`
It is  noticed that language model predicates **the masked word** in `base_model.py`.
I wonder why these lines are commented in `bert_cnn_model.py`? Performance?

**Comment by brightmart** [comment]
not related to perform but related to models.

if backbone model is Transformer, the output of model before classifier is a sequence, shape as ［sequence_length, d_model」. It use the last hidden state in the position of masked word as feature, and send to classifier.

but we replace backbone network from transformer to textcnn,we are using a different network and style, as output from textcnn is a hidden state, not a sequence of hidden states.

**Comment by wykdg** [comment]
how can text cnn predict the mask word without the position information?

**Comment by brightmart** [comment]
very good question! initially, I think as long as we have x and y, if we have x', then we can predict y'.
here x is the sentence with one word masked, y is the masked word.

then I thought that if one word is masked in a sentence, then the word is replace as special token [mask]. e.g. sentence now become 'x1 x2 x3 [mask] x5 x6'.  in this input, the model such as textcnn should already know the word in position is masked, it knows that. and it get representation of whole sentence, then predict a target which is the masked word. 

in a word, you can use the hidden states of in the masked word to represent the word, but it is also O.K. to use whole context to represent the word.

**Comment by NiHaoUCAS** [comment]
> very good question! initially, I think as long as we have x and y, if we have x', then we can predict y'.
> here x is the sentence with one word masked, y is the masked word.
> 
> then I thought that if one word is masked in a sentence, then the word is replace as special token [mask]. e.g. sentence now become 'x1 x2 x3 [mask] x5 x6'. in this input, the model such as textcnn should already know the word in position is masked, it knows that. and it get representation of whole sentence, then predict a target which is the masked word.
> 
> in a word, you can use the hidden states of in the masked word to represent the word, but it is also O.K. to use whole context to represent the word.
> 
> do you have any idea of still to use this position information? currently original textcnn max pooling and concat operation of textcnn will transform sequence of vectors to a vector.

80% is [mask] , 20% is still `real` words. 
whether we can concat the position embedding of [mask] to the output of textCNN(before dense layer)

**Comment by brightmart** [comment]
may be a good idea. can you have a try of it, then compare with current one. if result is better, just send a merge request.
